# -*- coding: utf-8 -*-
"""sum-of-two-digits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OTLE5lLK_jLzWHmZ-u22VMPuoQA5wxjS
"""

#1.1 Sum of Two Digits
first_digit = int(input("Enter the first digit: "))
second_digit = int(input("Enter the second digit: "))
sum = first_digit + second_digit
print("The sum of two digits is: ", sum)

